REST_API_HOST = '0.0.0.0'
REST_API_PORT = 5000
VALIDATION_ERROR = 'Validation error.'
NOT_AUTHORIZED = 'Not authorized.'
SUCCESSFUL = 'Operation successful.'
MESSAGE_STATE = 'Message {}.'
LOG_FORMAT = "%(asctime)s %(levelname)s %(module)s: %(message)s"
MQ_EXCHANGE_NAME = 'EXCHANGE'
MQ_MSG_QUEUE_NAME = 'MSG_QUEUE'
