version: "3"
services:

  rabbitmq:
    image: "rabbitmq:alpine"
    ports:
      - "5672:5672"

  listener:
    image: "bogart047/messenger"
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"
    command: sh -c "sleep 30 && python listener.py"

  sender:
    image: "bogart047/messenger"
    depends_on:
      - rabbitmq
    command: sh -c "sleep 30 && python sender.py"
