version: "3"
services:

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:alpine"
    restart: on-failure
    ports:
      - "5672:5672"
    networks:
      - backend

  postgres:
    container_name: postgres
    image: "postgres:alpine"
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./server_side/database:/var/lib/postgresql

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - "8888:8080"
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - logs:/var/log/dozzle

  listener-1:
    container_name: listener-1
    image: "dzamakhaiev/messenger"
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend
    environment:
      SERVICE_NAME: listener-1
    volumes:
      - logs:/messenger/server_side/logs
    command: sh -c "sleep 10 && git pull && gunicorn -w 2 -k gevent -b 0.0.0.0:5000 'listener:app'"

  listener-2:
    container_name: listener-2
    image: "dzamakhaiev/messenger"
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend
    environment:
      SERVICE_NAME: listener-2
    volumes:
      - logs:/messenger/server_side/logs
    command: sh -c "sleep 10 && git pull && gunicorn -w 2 -k gevent -b 0.0.0.0:5000 'listener:app'"

  sender-1:
    container_name: sender-1
    image: "dzamakhaiev/messenger"
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend
    environment:
      SERVICE_NAME: sender-1
    volumes:
      - logs:/messenger/server_side/logs
    command: sh -c "sleep 10 && git pull && python sender.py"

  sender-2:
    container_name: sender-2
    image: "dzamakhaiev/messenger"
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend
    environment:
      SERVICE_NAME: sender-2
    volumes:
      - logs:/messenger/server_side/logs
    command: sh -c "sleep 10 && git pull && python sender.py"

  nginx:
    container_name: nginx
    image: "dzamakhaiev/messenger-nginx"
    restart: on-failure
    depends_on:
      - listener-1
      - listener-2
    ports:
      - "5000:5000"
    networks:
      - backend
    command: sh -c "sleep 15 && nginx -g 'daemon off;'"

networks:
  backend:
    driver: bridge

volumes:
  logs: