version: "3"
services:

  rabbitmq-ci:
    container_name: rabbitmq
    image: "rabbitmq:alpine"
    restart: on-failure
    ports:
      - "5672:5672"
    networks:
      - backend-ci

  postgres-ci:
    container_name: postgres
    image: "postgres:alpine"
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - backend-ci
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./server_side/database:/var/lib/postgresql

  listener-1-ci:
    container_name: listener-1
    image: "dzamakhaiev/messenger"
    restart: on-failure
    depends_on:
      - rabbitmq-ci
      - postgres-ci
    networks:
      - backend-ci
    environment:
      SERVICE_NAME: listener-1
    volumes:
      - logs-ci:/messenger/server_side/logs
    command: sh -c "sleep 10 && git pull && gunicorn -w 2 -k gevent -b 0.0.0.0:5000 'listener:app'"

  listener-2-ci:
    container_name: listener-2
    image: "dzamakhaiev/messenger"
    restart: on-failure
    depends_on:
      - rabbitmq-ci
      - postgres-ci
    networks:
      - backend-ci
    environment:
      SERVICE_NAME: listener-2
    volumes:
      - logs-ci:/messenger/server_side/logs
    command: sh -c "sleep 10 && git pull && gunicorn -w 2 -k gevent -b 0.0.0.0:5000 'listener:app'"

  sender-ci:
    container_name: sender-1
    image: "dzamakhaiev/messenger"
    restart: on-failure
    depends_on:
      - rabbitmq-ci
      - postgres-ci
    networks:
      - backend-ci
    environment:
      SERVICE_NAME: sender-1
    volumes:
      - logs-ci:/messenger/server_side/logs
    command: sh -c "sleep 10 && git pull && python sender.py"

  nginx-ci:
    container_name: nginx
    image: "dzamakhaiev/messenger-nginx"
    restart: on-failure
    depends_on:
      - listener-1-ci
      - listener-2-ci
    ports:
      - "5000:5000"
    networks:
      - backend-ci
    command: sh -c "sleep 15 && nginx -g 'daemon off;'"

networks:
  backend-ci:
    driver: bridge

volumes:
  logs-ci: