name: Build and push Messenger

on:
  pull_request:
    branches:
      - master

  workflow_call:
    secrets:
      username:
        description: 'Docker hub username.'
        required: true
      password:
        description: 'Docker hub token.'
        required: true

jobs:

  deployment:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:

      - name: Build docker image for Messenger application
        run: docker build -t dzamakhaiev/messenger . --no-cache

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Push docker image for Messenger application
        run: docker push dzamakhaiev/messenger