name: Build and push Messenger

on:
  pull_request:
    branches:
      - master
      - develop

  workflow_call:
    inputs: {}

jobs:

  deployment:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:

      - name: Build docker image for Messenger application
        run: docker build -t dzamakhaiev/messenger . --no-cache

      - name: Push docker image for Messenger application
        run: docker push dzamakhaiev/messenger