name: Build and push MessCreate
on:
  pull_request:
    branches:
      - master

  workflow_call:
    inputs: {}

jobs:

  deployment:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - name: Build docker image for Messenger application
        run: docker build -t dzamakhaiev/messenger . --no-cache

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image for Messenger application
        run: docker push dzamakhaiev/messenger

      - name: Stop Messenger application to update containers
        run: docker compose -f messenger-prod.yaml stop

      - name: Remove docker outdated containers
        shell: bash
        run: docker rm -f listener-1, listener-2, sender-1, sender-2

      - name: Stop Messenger application to update containers
        run: docker compose -f messenger-prod.yaml start

      - name: Create and start Messenger application with updated containers
        run: docker compose -f messenger-prod.yaml up listener-1, listener-2, sender-1, sender-2 -d

      - name: Remove docker dangling images
        shell: bash
        if: always()
        run: |
          if $(docker images --filter "dangling=true" -q --no-trunc | grep -q .); then
                docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
          fi