name: Build and push MessCreate
on:
  pull_request:
    branches:
      - master

  workflow_call:
    inputs: {}

jobs:

  deployment:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - name: Build docker image for Messenger application
        run: docker build -t dzamakhaiev/messenger . --no-cache

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image for Messenger application
        run: docker push dzamakhaiev/messenger