name: Main deployment workflow

on:
  pull_request:
    branches:
      - master

jobs:

  pylint:
    uses: ./.github/workflows/pylint_report.yml

  unit:
    needs: pylint
    uses: ./.github/workflows/unit_tests.yml

  integration:
    needs: unit
    uses: ./.github/workflows/integration_tests.yml

  coverage:
    needs: integration
    uses: ./.github/workflows/coverage_report.yml

  deployment:
    secrets: inherit
    needs: coverage
    uses: ./.github/workflows/build_and_push.yml