name: Messenger CI pipeline

on:
  pull_request:
    branches:
      - master

jobs:

  pylint:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=8.0 $(git ls-files '*.py')

    - name: Update README badge
      run: echo '!PyLint' > README.md

  unit:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ "3.12" ]

    needs: pylint

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python3 -m unittest discover

  integration:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ "3.12" ]

    needs: unit

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run messenger application
        run: |
          docker compose -f ./messenger-ci.yaml up -d

      - name: Clone messenger-tests repository
        run: |
          git clone --depth 1 https://github.com/dzamakhaiev/messenger-tests.git

      - name: Run integration tests
        run: |
          python3 -m unittest discover

      - name: Close messenger application
        run: |
          docker compose -f ./messenger-ci.yaml down rabbitmq-ci postgres-ci listener-1-ci listener-2-ci sender-ci nginx-ci