name: Main deployment workflow

on:
  pull_request:
    branches:
      - master
      - develop

jobs:

  pylint:
    uses: ./.github/workflows/pylint.yml

  unit:
    needs: pylint
    uses: ./.github/workflows/unit_tests.yml

  integration:
    needs: unit
    uses: ./.github/workflows/integration_tests.yml

  coverage:
    needs: integration
    uses: ./.github/workflows/codecov_badge.yml